---
driver:
  name: docker
  use_sudo: false
  privileged: true
  username: kitchen
  provision_command: mkdir -p /run/sshd && apt-get -y install build-essential libffi-dev

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-18.04

verifier:
  name: inspec

suites:
  - name: server
    run_list:
      - recipe[scpr-consul]
    attributes:
      consul:
        servers:      nil
        service_mode: bootstrap
    verifier:
      inspec_tests:
        - test/integration/server
  - name: web_service_check
    run_list:
      - recipe[scpr-consul-test::web_service]
    attributes:
      consul:
        service_mode: server
        service_user: root
        service_group: root
