---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: server
    run_list:
      - recipe[scpr-consul::server]
    attributes:
      consul:
        servers:      nil
        service_mode: bootstrap
  - name: web_service_check
    run_list:
      - recipe[scpr-consul-test::web_service]
    attributes:
      consul:
        service_user: root
        service_group: root